Endpoints for updating account info and enabling\disabling MFA
ProtocolONE/qilin-store-api pull request #1
Opened 2019-06-03 07:57 UTC by shersh

2019-06-03 14:23 UTC, misterion requested changes

2019-06-03 14:23 UTC, misterion commented on pkg/api/account_router.go
> +	g.GET("/", router.getAccountInfo)
Сомнительный роут для получения информации о пользователе. Тут скорее `/me` или `/profile`

2019-06-03 14:23 UTC, misterion commented on pkg/api/account_router.go
> +	g.GET("/:userId", router.getAccountInfo)
/users/:userId ? почему всю роутится плоско без информации о ресурсе?

2019-06-03 14:23 UTC, misterion commented on pkg/interfaces/account.go
> +	GetAccount(userId string) (*model.User, error)
Не понимаю, почему методы авторизации, MFA и работы с профилем в базе намешаны в один сервис.

2019-06-04 15:34 UTC, sundagy commented on pkg/api/dto/account.go
> +		FirstName string         `json:"first_name"`
У нас разве не camelCase используется?

2019-06-04 15:34 UTC, sundagy commented on pkg/api/account_router.go
> +	if err := ctx.Validate(data); err != nil {
А в самой UpdateUserDTO validate не проставлен, так и предполагалось?

2019-06-04 16:43 UTC, shersh commented on pkg/api/dto/account.go
> +		FirstName string         `json:"first_name"`
Я честно говоря за то чтобы ввести snake_case во всех проектах. 
1. Это по-дефолту проставляется ide при наборе json
2. так проще писать и читать имхо
3. в некоторых проектах (Auth1 например) уже используется snake_case

@misterion твое слово?

2019-06-06 13:20 UTC, misterion commented on pkg/api/dto/account.go
> +		FirstName string         `json:"first_name"`
Он используется исключительно для json атрибутов потому что это основная рекомендация gofmt.

2019-06-06 13:20 UTC, misterion approved these changes

2019-06-06 13:47 UTC, merged